capture program drop putexcel_describe
program define putexcel_describe, rclass
    version 16

    tempfile pxlog

    /*
        Capture only the output generated by putexcel describe.
        name() creates a separate named log, so an existing main log
        does not need to be closed.
    */
    qui log using "`pxlog'", text replace name(_pxdescribe)

cap putexcel describe
	if _rc {
	
	display as error "no putexcel set is active"
	    qui log close _pxdescribe
	exit 198
	}
	
   quietly {
   
   noisily putexcel describe
   }

*TODO: control if there is a putexcel set	
	
  qui   log close _pxdescribe

    /*
        Read and parse the temporary log.
    */
    tempname fh
    file open `fh' using "`pxlog'", read text

    file read `fh' line

    local previous_key ""

    while r(eof) == 0 {

        /*
            Remove leading and trailing spaces.
        */
        local clean = strtrim(`"`line'"')

        /*
            Continuation lines produced when a long value wraps.
            Example:
                > Outputs\Tables_for_report\TAB-GUINEE.xlsx
        */
        if substr(`"`clean'"', 1, 1) == ">" & `"`previous_key'"' != "" {

            local continuation = strtrim(substr(`"`clean'"', 2, .))

            local current_value `"``previous_key''"'

            /*
                No space is inserted because a wrapped Windows path
                continues directly after the previous text.
            */
            local `previous_key' `"`current_value'`continuation'"'
        }

        /*
            Parse lines containing the vertical separator.
        */
        else if strpos(`"`clean'"', "|") {

            local pipe = strpos(`"`clean'"', "|")

            local label = strtrim(substr(`"`clean'"', 1, `pipe' - 1))
            local value = strtrim(substr(`"`clean'"', `pipe' + 1, .))

            /*
                Convert output labels into valid macro names.
            */
            if `"`label'"' == "Filename" {
                local key "filename"
            }
            else if `"`label'"' == "Filetype" {
                local key "filetype"
            }
            else if `"`label'"' == "Write mode" {
                local key "write_mode"
            }
            else if `"`label'"' == "Sheetname" {
                local key "sheetname"
            }
            else if `"`label'"' == "Locale" {
                local key "locale"
            }
            else if `"`label'"' == "Open file handle" {
                local key "open_file_handle"
            }
            else {
                local key ""
            }

            if `"`key'"' != "" {
                local `key' `"`value'"'
                local previous_key "`key'"
            }
        }

        file read `fh' line
    }

    file close `fh'

    /*
        Return the extracted values.
    */
    return local filename         `"`filename'"'
    return local filetype         `"`filetype'"'
    return local write_mode       `"`write_mode'"'
    return local sheetname        `"`sheetname'"'
    return local locale           `"`locale'"'
    return local open_file_handle `"`open_file_handle'"'
end